<a href="https://colab.research.google.com/github/SERGEYDJUM/believex/blob/main/KNN_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np

In [8]:
df=pd.read_csv('working.csv')

In [9]:
df_male_adults=df[(df['sex']==0)&(df['age']>=18)]
df_male_child=df[(df['sex']==0)&(df['age']<18)]
df_female_adults=df[(df['sex']==1)&(df['age']>=18)]
df_female_child=df[(df['sex']==1)&(df['age']<18)]

In [10]:
df_male_adults = df[(df['sex'] == 0) & (df['age'] >= 18)].dropna(subset=['LF_l'])
df_male_child = df[(df['sex'] == 0) & (df['age'] < 18)].dropna(subset=['LF_l'])
df_female_adults = df[(df['sex'] == 1) & (df['age'] >= 18)].dropna(subset=['LF_l'])
df_female_child = df[(df['sex'] == 1) & (df['age'] < 18)].dropna(subset=['LF_l'])


In [11]:
#for men
X_male_adults=df_male_adults[['LF_b', 'HF_b']]
y_male_adults=df_male_adults['LF_l']
#for boys
X_male_child=df_male_child[['LF_b', 'HF_b']]
y_male_child = df_male_child['LF_l']
#for women
X_female_adults=df_female_adults[['LF_b', 'HF_b']]
y_female_adults=df_female_adults['LF_l']
#for girls
X_female_child=df_female_child[['LF_b', 'HF_b']]
y_female_child=df_female_child['LF_l']

In [12]:
from sklearn.model_selection import train_test_split
#for men
X_train_male_adults, X_test_male_adults, y_train_male_adults_LF, y_test_male_adults_LF=train_test_split(X_male_adults, y_male_adults, test_size=0.2, random_state=100)
#for boys
X_train_male_child, X_test_male_child, y_train_male_child_LF, y_test_male_child_LF=train_test_split(X_male_child, y_male_child, test_size=0.2, random_state=100)
#for women
X_train_female_adults, X_test_female_adults, y_train_female_adults_LF, y_test_female_adults_LF=train_test_split(X_female_adults, y_female_adults, test_size=0.2, random_state=100)
#for girls
X_train_female_child, X_test_female_child, y_train_female_child_LF, y_test_female_child_LF=train_test_split(X_female_child, y_female_child, test_size=0.2, random_state=42)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
#for men
X_train_male_adults_scaled = scaler.fit_transform(X_train_male_adults)
X_test_male_adults_scaled = scaler.transform(X_test_male_adults)
#for boys
X_train_male_child_scaled = scaler.fit_transform(X_train_male_child)
X_test_male_child_scaled = scaler.transform(X_test_male_child)
#for women
X_train_female_adults_scaled = scaler.fit_transform(X_train_female_adults)
X_test_female_adults_scaled = scaler.transform(X_test_female_adults)
#for girls
X_train_female_child_scaled = scaler.fit_transform(X_train_female_child)
X_test_female_child_scaled = scaler.transform(X_test_female_child)

In [19]:
from sklearn.neighbors import KNeighborsRegressor
#for men
knn_male_adults = KNeighborsRegressor(n_neighbors=5, metric='manhattan')
knn_male_adults.fit(X_train_male_adults_scaled, y_train_male_adults_LF)
#for boys
knn_male_child = KNeighborsRegressor(n_neighbors=5, metric='euclidean', weights='uniform')
knn_male_child.fit(X_train_male_child_scaled, y_train_male_child_LF)
#for women
knn_female_adults = KNeighborsRegressor(n_neighbors=3, weights='distance', metric='euclidean')
knn_female_adults.fit(X_train_female_adults_scaled, y_train_female_adults_LF)
#for girls
knn_female_child = KNeighborsRegressor(n_neighbors=3, weights='distance', metric='manhattan')
knn_female_child.fit(X_train_female_child_scaled, y_train_female_child_LF)

KNeighborsRegressor(metric='manhattan', n_neighbors=3, weights='distance')

In [27]:
y_pred_male_adults=knn_male_adults.predict(X_test_male_adults_scaled)
y_pred_male_child=knn_male_child.predict(X_test_male_child_scaled)
y_pred_female_adults=knn_female_adults.predict(X_test_female_adults_scaled)
y_pred_female_child=knn_female_child.predict(X_test_female_child_scaled)

In [225]:
y_pred_male_adults, y_pred_male_child, y_pred_female_adults, y_pred_female_child

(array([22.28, 17.72, 22.28, 17.72, 18.68, 21.86]),
 array([27.624, 25.36 , 25.46 , 25.46 , 25.46 ]),
 array([10.41890864, 29.70930976, 16.8789085 , 24.05956598]),
 array([23.61938827, 25.50694592, 30.4353897 ]))

In [226]:
mean_male_adults=df_male_adults['LF_l'].mean()
mean_male_child=df_male_child['LF_l'].mean()
mean_female_adults=df_female_adults['LF_l'].mean()
mean_female_child=df_female_child['LF_l'].mean()
print(f'Mean for men: {mean_male_adults}')
print(f'Mean for boys: {mean_male_child}')
print(f'Mean for women: {mean_female_adults}')
print(f'Mean for girls: {mean_female_child}')

Mean for men: 24.94814814814815
Mean for boys: 25.574782608695653
Mean for women: 18.05
Mean for girls: 28.276363636363637


In [227]:
from sklearn.metrics import mean_squared_error
MSE_male_adults=mean_squared_error(y_test_male_adults_LF, y_pred_male_adults)
print(f'MSE for men: {MSE_male_adults}')
MSE_male_child=mean_squared_error(y_test_male_child_LF, y_pred_male_child)
print(f'MSE for boys: {MSE_male_child}')
MSE_female_adults=mean_squared_error(y_test_female_adults_LF, y_pred_female_adults)
print(f'MSE for women: {MSE_female_adults}')
MSE_female_child=mean_squared_error(y_test_female_child_LF, y_pred_female_child)
print(f'MSE for girls: {MSE_female_child}')

MSE for men: 19.23493333333334
MSE for boys: 46.1388352
MSE for women: 88.91780124796294
MSE for girls: 78.91869639206818


In [228]:
from sklearn.metrics import mean_absolute_error
MAE_male_adults=mean_absolute_error(y_test_male_adults_LF, y_pred_male_adults)
print(f'MAE for men: {MAE_male_adults}')
MAE_male_child=mean_absolute_error(y_test_male_child_LF, y_pred_male_child)
print(f'MAE for boys: {MAE_male_child}')
MAE_female_adults=mean_absolute_error(y_test_female_adults_LF, y_pred_female_adults)
print(f'MAE for women: {MAE_female_adults}')
MAE_female_girls=mean_absolute_error(y_test_female_child_LF, y_pred_female_child)
print(f'MAE for girls: {MAE_female_girls}')

MAE for men: 2.826666666666668
MAE for boys: 5.299200000000001
MAE for women: 7.297781028863286
MAE for girls: 7.012758700896936
